title: AMEER OSMAN YOUSUFZIA
# logo:
description: "My name is Ameer Osman Yousufzia. I am a second year student at the University of Manchester, studying Computer Science & Mathematics"
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
